comment:
  layout: "diff, files"
  behavior: default
  require_changes: true
  require_base: yes
  require_head: yes
  branches: null

coverage:
  notify:
    gitter:
      default:
        url: "secret:T9UBeoPLvCow+b8GS/yW0tsZ0H5uElK83g2y/ICn9UE+15yhtVz7azR/+SS33+P/tYGzO1aCPXt0/s+X3k9rtfj8B3GnHcF/kLD7GgLTRjRzIwiAg5ur7JyacHuF09Pk"
        threshold: 1%
