name: Lint and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
        vault-version:
          - 1.4.7
          - 1.5.8
          - 1.6.4
          - 1.7.1

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: pip install -r requirements-dev.txt

    - name: Install Vault and Consul (for integration tests)
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        echo "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
          | sudo tee /etc/apt/sources.list.d/hashicorp.list

        sudo apt update \
          -o Dir::Etc::sourceparts="-" \
          -o APT::Get::List-Cleanup="0" \
          -o Dir::Etc::sourcelist="sources.list.d/hashicorp.list"

        sudo apt install \
          consul \
          vault-enterprise \
          ;

        # We disble cap_ipc_lock here as its generally incompatabile with GitHub
        # Actions' runtime environments.
        sudo setcap cap_ipc_lock= /usr/bin/vault

    - name: Lint with black
      run: black --check .

    - name: Test with pytest
      run: pytest --cov=hvac tests/

    - name: Codecov - Process coverage
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        verbose: false
